import { rmSync, lstatSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { relative, join } from 'node:path';
import { execFileSync } from 'node:child_process';

const root = fileURLToPath(new URL('..', import.meta.url));
const output = fileURLToPath(new URL('../out', import.meta.url));
if (relative(root, output) !== 'out') { throw new Error('Unexpected generated test output path.'); }
try {
  const stat = lstatSync(output);
  if (stat.isSymbolicLink() || !stat.isDirectory()) { throw new Error('Generated test output must be a regular directory.'); }
} catch (error) { if (error.code !== 'ENOENT') { throw error; } }
// This directory is exclusively generated by TypeScript and excluded from Git.
// Remove stale compiled tests when their source has been deleted or renamed.
rmSync(output, { recursive: true, force: true });
execFileSync(process.execPath, [join(root, 'node_modules/typescript/bin/tsc'), '-p', '.', '--outDir', output], {
  cwd: root, stdio: 'inherit', windowsHide: true,
});
